"""Initial migration.

Revision ID: 6bbf93445088
Revises: 
Create Date: 2024-08-09 19:06:30.146353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbf93445088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_api_ged_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pasta', sa.String(length=255), nullable=False),
    sa.Column('npj', sa.String(length=255), nullable=False),
    sa.Column('cnj', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('_file_', sa.Text(), nullable=True),
    sa.Column('id_download', sa.Text(), nullable=True),
    sa.Column('link_download', sa.Text(), nullable=True),
    sa.Column('data_cricao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_file_'),
    sa.UniqueConstraint('id_download')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_api_ged_tools')
    op.drop_table('post')
    # ### end Alembic commands ###
